remove .sh extension from extlinux scripts
Signed-off-by: John Clark <inindev@gmail.com>

diff --git a/files/dtb_cp b/files/dtb_cp
--- a/files/dtb_cp
+++ b/files/dtb_cp
@@ -13,18 +13,18 @@ target="/boot/<DTB_FILE>-${version}"
 
 # passing the kernel version is required
 if [ -z "${version}" ]; then
-	echo >&2 "dtb_cp.sh: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
+	echo >&2 "E: dtb_cp: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
 	exit 2
 fi
 
 if [ -f "${source1}" ]; then
-	echo "dtb_cp.sh: installing ${source1} to ${target}"
+	echo "I: dtb_cp: installing ${source1} to ${target}"
 	install -m 644 "${source1}" "${target}"
 elif [ -f "${source2}" ]; then
-	echo -n "dtb_cp.sh: symlink "
+	echo -n "I: dtb_cp: symlink "
 	ln -sfv "$(basename "${source2}")" "${target}"
 else
-	echo >&2 "dtb_cp: neither ${source1} nor ${source2} not found"
+	echo >&2 "E: dtb_cp: neither ${source1} nor ${source2} not found"
 	exit 3
 fi
 
